<?php

	function echoCSSFont($page) {
		
		echo "\n<!--READABILITY FONT SELECTION START: Auto-generated-->\n";
		
		$disableFont = isset($_GET["readability"]) ? $_GET["readability"] : 0;
		$url = '';
		$front = 0;
		$main = 1;
		
		if ($disableFont != 1) {
			if ($page == 'front') {
				$url = '/css/front_font.css';
			}
			else if ($page == 'main') {
				$url = '/css/main_font.css';
			}
		}
		else {
			if ($page == 'front') {
				$url = '/css/front_font_readable.css';
			}
			else if ($page == 'main') {
				$url = '/css/main_font_readable.css';
			}
		}
		
		echo '<link rel="stylesheet" type="text/css" href="'.$url.'">';
		
		echo "\n<!--READABILITY FONT SELECTION END: Auto-generated-->\n";
	}
	
	function echoLink($content, $url) {
		
		echo "<!--Autogenerated link (".$content.") start-->";

		$disableFont = isset($_GET["readability"]) ? $_GET["readability"] : 0;
		if ($disableFont != 1) {
			echo '<a href="'.$url.'">'.$content.'</a>';
		}
		else {
			echo '<a href="'.$url.'?readability=1">'.$content.'</a>';
		}
		
		echo "<!--Autogenerated link (".$content.") end-->";
	}

	
	function echoLinkTitle($content, $url) {
		
		echo "<!--Autogenerated title link (".$content.") start-->";
		
		$disableFont = isset($_GET["readability"]) ? $_GET["readability"] : 0;
		if ($disableFont != 1) {
			echo '<a href="'.$url.'" class="linkTitle">'.$content.'</a>';
		}
		else {
			echo '<a href="'.$url.'?readability=1" class="linkTitle">'.$content.'</a>';
		}
		
		echo "<!--Autogenerated title link (".$content.") end-->";
	}
	
	function echoReadabilitySwitchLink() {
		
		echo "\n<!--READABILITY SWITCH LINK START: Auto-generated-->\n";
		
		$text = "Stylish font: ";
		$readability0Text = "ON";
		$readability1Text = "OFF";
		
		$disableFont = isset($_GET["readability"]) ? $_GET["readability"] : 0;
		if ($disableFont != 1) {
			echo '<a href="?readability=1"><div id="readabilityBox"><span id="readabilityLink">'.$text.$readability0Text.'</span></div></a>';
		}
		else {
			echo '<a href="?readability=0"><div id="readabilityBox"><span id="readabilityLink">'.$text.$readability1Text.'</span></div></a>';
		}
		
		echo "\n<!--READABILITY SWITCH LINK END: Auto-generated-->\n\n";
	}
	
	
	function echoNewContentBox() {
		echo "<!--Autogenerated new content box start-->";
		echo '</div><div class="contentBox">';
		echo "<!--Autogenerated new content box end-->";
	}
	
	function echoTitle() {
		
		echo "\n<!--TITLE START: Auto-generated-->\n";
		
		$params = func_get_args();
		$pageDepth = $params[0];
		

		$url = '/';
		
		echo '<h1>';
		echoLinkTitle('Robin &Aring;stedt', $url );
		echo '/';
		
		if ($pageDepth > 0) {
			for ($i = 1; $i <= $pageDepth; $i++) {
				if ($i < $pageDepth) {
					$url = $url.$params[$i].'/';
					echoLinkTitle($params[$i], $url);
				}
				else {
					echo $params[$i];
				}
				echo '/';
			}
		}
		echo '</h1><p>';
		echoLink("Back", $url);
		echo ' | <a target="_blank" href="https://creativecommons.org/licenses/by-nc-sa/3.0/">CC BY-NC-SA 3.0</a> applies when no license is included.</p>';
		
		if (count($params) > $pageDepth + 1) {
			$tableOfContentsIndex = $pageDepth + 2;
			$tableOfContentsSize = $params[$pageDepth + 1];
			if ($tableOfContentsSize > 0) {
				
				echoNewContentBox();
				
				echo '<h2>Table of contents</h2><p>';
				
				for ($i = 0; $i < $tableOfContentsSize; $i++) {
					$linkText = $params[$tableOfContentsIndex + $i];
					$url = '#'.preg_replace('/[^a-zA-Z0-9]+/', '', $linkText);
					echo '<a href="'.$url.'">'.$linkText.'</a>';
					if ($i < $tableOfContentsSize - 1) {
						echo '<br />';
					}
				}
				
				echo '</p>';
			}
		}
		
		echo "\n<!--TITLE END: Auto-generated-->\n\n";

	}
	
	
?>
