#!/bin/bash

set -ex

# The one generated by podman-compose is broken, lacks --in-pod 1
cp podman-compose@.service ~/.config/systemd/user/podman-compose@.service
systemctl --user daemon-reload

systemctl --user stop 'podman-compose@website'
podman-compose --in-pod 1 down || true
podman volume rm website_webroot || true
podman-compose --in-pod 1 build
systemctl --user enable --now 'podman-compose@website'
