FROM certbot/certbot:latest

#CMD certbot certonly --nginx

# podman compose --in-pod 1 run --rm certbot certonly --webroot --webroot-path /var/www/robinastedt.com/ -d robinastedt.com


#CMD certonly --webroot --webroot-path /var/www/robinastedt.com/ --dry-run -d robinastedt.com
# CMD ["certonly", "--webroot", "--webroot-path", "/var/www/robinastedt.com/", "--dry-run", "-d", "robinastedt.com" ]
